spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafedp
    username: root
    password: Brasil@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
